name: redeploy

on:
  # We want to re-deploy daily to update any dynamic content on the page (e.g. favorite music, age)
  schedule:
    - cron: "42 0 * * *"

  # Manual
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-24.04
    steps:
      - env:
          DEPLOY_HOOK: ${{ secrets.DEPLOY_HOOK }}
        run: |
          curl -X POST "${DEPLOY_HOOK}"
